language: ruby
rvm:
- 2.1
# Assume bundler is being used, install step will run `bundle install`.
install:
  - bundle install
script: 
  - bundle exec jekyll build

# branch whitelist
branches:
  only:
  - source

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer