language: ruby
rvm:
- 2.1
install:
- bundle install
script:
- bundle exec rake site:publish_ci
branches:
  only:
  - source
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: f31TKahv1xJW7BBzUEWDeAoe0AVB8phBOsBrSweFe0/JlLdLyO6yTWZfhbURSsrzmRbYqOObp4xkHoizD+Yu+rnXArRRLTXsUPflu1UZxtC3VzIAZfiq7uyIxRQOypKMi061A4J97cTh/Jka3BqgOVHFZzLlmiDSqRCMWJMb5ZWU6OUkV++uduqEIuDJW/v7QkwkNb7NXBch1pziTfOHA+83k8Ycns4eCEpBWB0OlgVuKwQDG5X2e+qilJYmSxIR5zqSOPeW0FwThCv05MG6JTwWdM6bbxAC4CKTyUSlJ2bNC/uVBK6eJavdJzMfCHD+EzB+Wno6kLkfclEKt57Dhwk2ii1SF2bsFmg4eskgoSLd3+kCGc5DMS+FEb+VsTAlCqCeyA7T4wVyHTtrPBSkMCIUZg4sxcdksPKe/Rq0hKJUX6xLh+5gYNid8sSNdXOO4M4bRCadMoqXxOZ8YwpNlIj8o3tXNWnJYqGxhopYR9q7CFdzpDfclQ8sEQpTc39RQ1ZPS9fLpQe3/1CbZt1XGWGYjsPQO4nx6gioK7pvomQ3rrsrM7o9Sbooq7cNp1Pbk3Kla5gi0pRggZFiF3qE9utzwl2LKuXrVRHgVP0mg2OVqXFOSAtBBejAPf41FgGvsTDYsPrTIkoUoplTxxG2NaVx3JJT3Cc2YyjctxoVXa4=

notifications:
  slack:
    secure: KPtOOi2bYD0GCDvbLWUk9pDK35mB/QUroMW6LDQpABu3Z1/7RxHkkemxJgMqSrOxTbGqatDQ/MJ8Vh5dLfG5t3oa56K11nB7EzeJKbgqOyj3hdSB2kbNF/W7+qaalydwJExK1/ZJ9jr+UbaPeJFAHDT1wM4OBCWhdqhMiPoQ1cK3TSKAuSOpxqtWTWOmWHNt4fWgiJEA4PDmFfxhg/vGQkbjI2NU9pFWGNE+uKmvIqJ6Ejrf4KFqO2xtfjuSYnwAs2G/E21/NsKo+G3F9prKpD6aUad5xk/nic+sajeoo8WJ4z6S7aVb44Avxmmw0tPCv6nJnobjD8zIcQYWjURVveqiH4oCiRjiEEPPAjY8Z+6hhps2k2U1pfFGulM8p2IZr6I4dDB3r0F8jXMFzX2yQDF+gbjlDm7fbhLRGD+BlnQXydhRqch95r6ueCSgSSOEE5Y1fezoO5Vn0uVtx/GdfD7JTmUc/LEwI3CXZCIhtF1xsJi+2Y+8I9a2dQwUF55pnxOruXTKjG2MWx3yK0xXts/fLoDecoDTnsgTAbae0Cu3cn2XaIyPi+fTm2RuUcq1Y1EKE/wT97KXM1vyXgW4T5Uubr41yCAIj0JF/M31oUMEXuDgXwbXfxnwgivlrX/64ILSaBjzL/Is92vAbUYBgAtFWblQT2U6FZS+XEAzfUc=
